Remove and rename duplicate models in api.yml, change some enum name
bangumi/api pull request #123
Opened 2022-04-23 14:27 UTC by EverettSummer

- Remove SubjectType from api.yml, reference this model from v0.yaml.
- Remove UserGroup from api.yml, reference this model from v0.yaml.
- Rename Subject in api.yml to SubjectLegacy to avoid naming conflict with v0.yaml
- Add a script to reset version.json to default after running `npm run build:local`
- Sync v0.yaml from bangumi/server repo

2022-04-23 14:29 UTC, Trim21 commented on open-api/api.yml
> +          $ref: "v0.yaml#/components/schemas/UserGroup"
`openapi-merge-cli` 能正确处理这种跨文件引用吗

2022-04-23 14:30 UTC, EverettSummer commented on open-api/api.yml
> +          $ref: "v0.yaml#/components/schemas/UserGroup"
好吧，好像不能，我看看怎么办

2022-04-23 14:31 UTC, Trim21 commented on open-api/api.yml
> +          $ref: "v0.yaml#/components/schemas/UserGroup"
正常的`#/components/schemas/UserGroup` 就行了吧，反正合并之后都成了一个文件了

2022-04-23 14:41 UTC, Trim21 commented
话说 `build:local` 其实没必要更新日期的

2022-04-23 14:48 UTC, EverettSummer commented
如果不使用write-data.js的脚本，生成的文件最后会缺少info信息，导致dist.json是个非法文件，我还是要用这个项目的dist.json去generate sdk的

2022-04-23 14:49 UTC, EverettSummer commented
我试试先run一下这个https://github.com/APIDevTools/json-schema-ref-parser，然后再运行openapi-merge-cli

2022-04-23 14:51 UTC, Trim21 commented
> 如果不使用write-data.js的脚本，生成的文件最后会缺少info信息，导致dist.json是个非法文件，我还是要用这个项目的dist.json去generate sdk的

那把 `version.json` 的内容改成 `{"info":{"version":""}}` 就好了

2022-04-23 14:54 UTC, EverettSummer commented
我觉得无妨，正好sdk的注释里面也会用到，反正已经不会把version带进git了。而加的脚本并不会影响Github Action的build

2022-04-23 14:55 UTC, Trim21 commented
起码不能像你现在这么写...现在这么写的话`npm run build`失败的话不会运行后面那个重置命令的

2022-04-23 15:01 UTC, EverettSummer commented
我觉得也没关系啊，只要有一次成功运行`npm run build:local`，就可以了，而且这个就是个懒人防呆工具，防止我手滑把version.json commit了，实际上我原本考虑删掉version，然后放到gitignore里。既然是生成的文件。。

2022-04-23 15:37 UTC, EverettSummer commented on open-api/api.yml
> +          $ref: "v0.yaml#/components/schemas/UserGroup"
我把所有的#ref改回了 `#/components/schemas` 形式，也恢复了删除的那些model，加了一个脚本，自动删除api.yml的model，然后生成一个api-gen.json，再用这个文件去merge，避免了duplicate

2022-04-23 15:38 UTC, EverettSummer commented
增加了一个脚本`.github/scripts/remove-dup.js`
`api.yml`恢复为被删除前的状态。
通过脚本删除，之后生成`api-gen.json`，并使用这个文件进行merge

2022-04-23 15:39 UTC, Trim21 commented on open-api/api.yml
> +          $ref: "v0.yaml#/components/schemas/UserGroup"
没必要吧，直接把api.yaml里面的重复type删了不就行了

2022-04-23 15:41 UTC, EverettSummer commented
> 我觉得也没关系啊，只要有一次成功运行`npm run build:local`，就可以了，而且这个就是个懒人防呆工具，防止我手滑把version.json commit了，实际上我原本考虑删掉version，然后放到gitignore里。既然是生成的文件。。

`npm run build:local`里面用到的script均不会影响Github Action用到的`npm run build`，所以无需担心break任何东西

2022-04-23 15:48 UTC, Trim21 commented
有点太复杂了吧...

2022-04-23 15:51 UTC, EverettSummer commented
如果直接删了 `api.yml`里面 重复的，似乎就导致 `api.yml`  不是合法的openapi文件。所以可能现在这么做是最简单了。

2022-04-23 15:51 UTC, Trim21 commented
那就不是呗- -

2022-04-23 15:54 UTC, EverettSummer commented
或这样如何，删除 api.yml 重复的文件，然后merge之前，用脚本把 跨文件的reference 改回local的reference，就是去掉前面的文件路径。这样比较清晰，也避免了yml里面有重复定义

2022-04-23 16:00 UTC, Trim21 commented
要不就用 urls 和 topbar plugin

2022-04-23 16:12 UTC, EverettSummer commented
抱歉没有用过你说的，也没搜到相关的信息。可否详述。

2022-04-23 16:13 UTC, Trim21 commented
https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

2022-04-23 16:14 UTC, Trim21 commented
```html
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
      window.onload = function () {
        window.ui = SwaggerUIBundle({
          urls: ["./api.yaml", "./v0.yaml"],
          dom_id: "#swagger-ui",
          layout: "BaseLayout",
          deepLinking: true,
          presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIBundle.SwaggerUIStandalonePreset,
          ],
        });
      };
    </script>
```

2022-04-23 16:19 UTC, EverettSummer commented
这样会出现两个分离的spec的文档吗（在topbar上的dropdown选择），也就是说你不想merge这两个api文件了吗？

2022-04-23 16:21 UTC, EverettSummer commented
hmm，对于我来说，可能更关心code gen的部分，所以即使不合并，还是需要避免出现同样的定义的，而且我也看看不合并要怎么generate code。

2022-04-23 16:21 UTC, Trim21 commented
我是觉得你现在合并这两个文件的方法太复杂了...



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年4月24日(星期天) 凌晨0:20
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [bangumi/api] Remove and rename duplicate models in api.yml, change some enum name (PR #123)





 
这样会出现两个分离的spec的文档吗（在topbar上的dropdown选择），也就是说你不想merge这两个api文件了吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2022-04-23 16:28 UTC, EverettSummer commented
如果openapi-merge一开始就支持把 `v0.yaml#/components/schemas/UserGroup` 改回 `#/components/schemas/UserGroup` 我可能就不用折腾这2个小时了。我去找他们的github repo，结果发现相关的issue还是open的，既然我们这里的path都是固定的，为何不自己写个脚本多简单。就几行的事情。没什么复杂的，比起把之前的架构拆了重构要省事多了。

2022-04-23 16:32 UTC, EverettSummer commented
现在要达到的目标：
1. 生成一个单独的openapi json文件
2. 不出现重复的schema定义
3. 因为v0.yaml来自别的repo，所以依然需要跟api.yml分开保存
4. 为了避免日后有人用什么authoring的工具说api.yml不合法，所以需要让其合法，所以该ref的path比较合理

为了达到这个目的：
1. 移除api.yml重复的schema
2. 把api.yml对这些schema的ref加上一个v0.yaml的前缀，是一种合法的openapi reference形式
3. 在merge之前去掉这些前缀

这就是我想要说到办法，其实就是把现在的remove-dup.js脚本再改一下就行

2022-04-23 16:40 UTC, Trim21 commented
`api.yml`&nbsp;唯一会有的更新是删除旧api了，不会再有什么其他像样的更新了




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年4月24日(星期天) 凌晨0:32
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [bangumi/api] Remove and rename duplicate models in api.yml, change some enum name (PR #123)





 
现在要达到的目标：
  
生成一个单独的openapi json文件
 
不出现重复的schema定义
 
因为v0.yaml来自别的repo，所以依然需要跟api.yml分开保存
 
为了避免日后有人用什么authoring的工具说api.yml不合法，所以需要让其合法，所以该ref的path比较合理
  
为了达到这个目的：
  
移除api.yml重复的schema
 
把api.yml对这些schema的ref加上一个v0.yaml的前缀，是一种合法的openapi reference形式
 
在merge之前去掉这些前缀
  
这就是我想要说到办法，其实就是把现在的remove-dup.js脚本再改一下就行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2022-04-23 16:44 UTC, EverettSummer commented
我看到你有个draft PR还改了这个文件，加了API，
我先把我的想法更新一下，你看一下吧。其实很简单，也不容易出错。

2022-04-23 16:45 UTC, Trim21 commented
那个也应该放到新文件，从别的仓库同步的

2022-04-23 17:33 UTC, Trim21 requested changes

2022-04-23 17:33 UTC, Trim21 commented on .github/scripts/rewrite-ref-path.js
> +function loadFile(p) {
这就没必要再包一层了吧...

而且nodejs的fs默认编码也是utf8，没必要再传一遍

2022-04-24 04:03 UTC, EverettSummer commented on .github/scripts/rewrite-ref-path.js
> +function loadFile(p) {
哦，这个之前是loadYAML，之后就顺手这么写了。已经改了，虽然encoding我一般习惯explicit以免弄错。不过writefile确实默认是utf8，readfile还是需要指定的

2022-04-24 14:48 UTC, merged

2022-04-24 14:49 UTC, Trim21 commented
有点问题 https://github.com/bangumi/api/runs/6147338236?check_suite_focus=true

2022-04-24 15:03 UTC, EverettSummer commented
我寫錯path了，`- run: node .github/script/rewrite-ref-path.js` scripts少打了個s

2022-04-24 15:13 UTC, Trim21 commented
能不能再提个PR修一下（

2022-04-30 22:49 UTC, Trim21 commented
- - 这个问题有一个简单地解决办法 用 https://github.com/APIDevTools/json-schema-ref-parser 这个库的bundle api就可以解决了